const food = [
    {
        name: "Baked Potato Soup",
        img:"https://www.allrecipes.com/thmb/JdeZHt9jQjZct4AS0oP9kssDv8I=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/5867379-361fd5f1eb254d38b7913e0abfaee07a.jpg",
        timeToPrepare: "40 min",
        ingredients: [
            "Bacon",
            "Butter",
            "Flour",
            "Baked Potatoes",
            "Milk",
            "Green Onions",
            "Seasonings",
            "Cheese",
            "Sour Cream"
        ],
        listOfSteps: [
            "Cook the bacon.",
            "Melt the butter, then whisk in the flour and milk.",
            "Add the potatoes and onions and bring to a boil.",
            "Reduce to a simmer, then stir in the remaining ingridients.",
            "Cook until the cheese is melted."
        ],
        cuisine: "peru",
        favorite: true
    },
    {
        name: "Homemade Beef Stew",
        img: "https://healthyfitnessmeals.com/wp-content/uploads/2020/01/Classic-beef-stew-4.jpg",
        timeToPrepare: "2 hrs 35 mins",
        ingredients: [
            "3 tablespoons vegetable oil",
            "2 pounds cubed beef stew meat",
            "4 cubes beef bouillon, crumbled",
            "4 cups water",
            "1 teaspoon dried rosemary",
            "1 teaspoon dried parsley",
            "½ teaspoon ground black pepper",
            "3 large potatoes, peeled and cubed",
            "4 carrots, cut into 1 inch pieces",
            "4 stalks celery, cut into 1 inch pieces",
            "1 large onion, chopped",
            "2 teaspoons cornstarch",
            "2 teaspoons cold water"
        ],
        listOfSteps: [
            "Heat oil in a large pot or Dutch oven over medium-high heat; add beef and cook until well browned.",
            "Dissolve bouillon in 4 cups water and pour into the pot; stir in rosemary, parsley, and pepper. Bring to a boil; reduce heat to low, cover, and simmer for 1 hour. Stir in potatoes, carrots, celery, and onion.",
            "Dissolve cornstarch in 2 teaspoons of cold water; stir into stew. Cover and simmer until beef is tender, about 1 hour."
        ],
        cuisine: "american",
        favorite: false
    },
    {
        name: "Panettone",
        img:"https://www.elmundoeats.com/wp-content/uploads/2022/11/RC-Panettone-on-a-wooden-plate.jpg",
        timeToPrepare: "4 hrs",
        ingredients: [
            "⅓ cup warm water (110 degrees F/45 degrees C)",
            "2 (.25 ounce) packages active dry yeast",
            "4 cups all-purpose flour",
            "½ cup warm milk",
            "⅔ cup white sugar",
            "4 large eggs",
            "2 large egg yolks",
            "1 teaspoon vanilla extract",
            "12 tablespoons unsalted butter",
            "2 cups candied mixed fruit",
            "2 ½ teaspoons grated lemon zest",
            "2 tablespoons orange zest",
            "2 tablespoons butter, melted",
            "1 egg yolk",
            "1 tablespoon cream",
            "3 (7 x 4-inch) round paper panettone molds"
        ],
        listOfSteps: [
            "To make sponge, warm a small bowl by rinsing it with hot water. Pour in warm water and sprinkle 1 package yeast on it. Let stand until yeast has dissolved. Stir in 1/2 cup flour, cover with plastic wrap, and let stand 30 minutes, or until doubled. Sprinkle remaining yeast over warm milk. Let stand until dissolved. Beat together sugar, eggs, egg yolks, and vanilla. Stir in milk-yeast mixture. Add sponge and stir until well incorporated.",
            "Combine butter and remaining 3 ½ cups flour until crumbly. Slowly pour in egg mixture and beat on high speed 3 to 4 minutes, until dough is elastic looking and long strands form. Beat in fruit and zests. Turn dough into oiled bowl, cover with plastic wrap, and leave in a warm place to rise until doubled, about 2 to 3 hours.",
            "Brush inside of three 7 x 4-inch paper molds with melted butter. Turn dough out onto a lightly floured work surface and knead a few times to deflate. Divide dough into 3 pieces. Roll each piece into a ball and drop into prepared molds; place on a baking sheet about 4-inches apart and cover loosely with plastic wrap. Let rise in a warm place until doubled again, about 2 hours.",
            "Preheat the oven to 400 degrees F (200 degrees C). Cut an X in top of each loaf with oiled scissors. Combine egg yolk with cream. Brush tops of loaves lightly with egg wash.",
            "Place baking sheet with loaves in bottom 1/3 of preheated oven. After 10 minutes, lower heat to 375 degrees F (190 degrees C). Continue to bake for 30 more minutes; if tops get too brown, cover with foil. Loaves are done when a wooden skewer inserted into centers comes out clean. Cool on wire rack."
        ],
        cuisine: "italian",
        favorite: false
    },
    {
        name: "Soft Gingerbread Cookies",
        img: "https://www.savorynothings.com/wp-content/uploads/2014/11/gingerbread-recipe-image-1.jpg",
        timeToPrepare: "25 mins",
        ingredients: [
            "1 (15 ounce) package spice cake mix, Duncan Hines® Perfectly Moist Spice Cake Mix",
            "1 1/2 teaspoons ground ginger",
            "1/4 teaspoon ground cloves",
            "1 large egg, at room temperature",
            "1/3 cup vegetable oil",
            "1/4 cup molasses"
        ],
        listOfSteps: [
            "Preheat the oven to 350 degrees F (180 degrees C).  Line a baking sheet with parchment.",
            "Whisk together cake mix, ginger, and cloves. Stir egg, oil, and molasses into the cake mix mixture until combined.",
            "Using a cookie scoop or tablespoon, drop the dough about two inches apart onto the prepared baking sheet.",
            "Bake in the preheated oven until cookies are set, 10 to 12 minutes. Cool on the baking sheet for 5 minutes, then transfer to a wire rack to cool completely."
        ],
        cuisine: "greek",
        favorite: true
    },
    {
        name: "sandwich",
        img: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fmarketsandwich.com%2Fwp-content%2Fuploads%2F2019%2F05%2FMarket_Sandwich-Mega-SmokedHamCheese-basic-768x768.jpg&f=1&nofb=1&ipt=628132f960c0689b95a7c900b29925b615be9fc5054db5aa99682d47b1cbfcd4&ipo=images",
        timeToPrepare: "2 min",
        ingredients: ["bread", "ham", "cheese"],
        listOfSteps: ["cut bread", "add ham", "add cheese"],
        cuisine: "english",
        favorite: true,
    },
    {
        name: "bacon-omelette",
        img: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.dontgobaconmyheart.co.uk%2Fwp-content%2Fuploads%2F2020%2F09%2Fbacon-cheese-omelette.jpg&f=1&nofb=1&ipt=7c94b0d1ea87cc25c60ffc9d72ac2b57172c29366b05ba10bf046eaf1c5e588d&ipo=images",
        timeToPrepare: "10 min",
        ingredients: ["eggs", "butter", "bacon"],
        listOfSteps: ["melt butter", "fry bacon", "add 2 eggs"],
        cuisine: "french",
        favorite: false,
    },
    {
        name: "PBJ",
        img: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Flivenaturallymagazine.com%2Fwp-content%2Fuploads%2F2016%2F01%2Fpg-22-shutterstock_172741412.jpg&f=1&nofb=1&ipt=a97e9ca7dcc3c626ecf99a1d357eef91448584c9fcb009c8c382683904e11b18&ipo=images",
        timeToPrepare: "5 min",
        ingredients: ["peanut butter", "bread", "jam"],
        listOfSteps: ["cut bread", "spread PB", "spread jam"],
        cuisine: "american",
        favorite: true,
    },
    {
        name: "hot-dog",
        img: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fpotatorolls.com%2Fwp-content%2Fuploads%2F2020%2F10%2FBasic-Hot-Dogs.jpg&f=1&nofb=1&ipt=40075df9c611a414d2451dd260c6024a8edec697d806421697f70c15bb871a1c&ipo=images",
        timeToPrepare: "10 min",
        ingredients: ["bread", "wurst", "ketchup", "mustard"],
        listOfSteps: ["boil wurst", "add wurst in bread", "add ketchup", "add mustard"],
        cuisine: "american",
        favorite: true,
    },
    {
        name: "White Dragon Noodles",
        img: "https://www.foxvalleyfoodie.com/wp-content/uploads/2015/07/spicy-dragon-noodles-recipe.jpg",
        timeToPrepare: "15 min",
        ingredients: ["dried noodles", "garlic", "mirin", "sake", "soy sauce", "sesame oil", "vinegar", "green onions"],
        listOfSteps: ["Cook the noodles", "Combine ingrediënts in a bowl, except the noodles", "Heat the oil in a wok, add the rest and cook for 5min", "Serve in a bowl, topped with sesame seeds and green onion"],
        cuisine: "movie",
        favorite: true
    },
    {
        name: "Special Bell Peppers & Beef",
        img: "https://static.wikia.nocookie.net/cowboybebop/images/3/38/1_BellPeppers.png/revision/latest/scale-to-width-down/200?cb=20090907195430",
        timeToPrepare: "30 min",
        ingredients: ["flank steak", "garlic", "shiitake mushrooms", "green bell peppers", "soy sauce", "rice vinegar", "fresh ginger", "green onions"],
        listOfSteps: ["Heat the cooking oil", "Add the steak and cook in for 2-3 min", "Add garlic, mushrooms and peppers, cook for 2-3 min", "Add soy sauce; vinegar and ginger, boil for a minute", "Combine everything in a hot pan, and get ready to serve"],
        cuisine: "movie",
        favorite: false
    },
    {
        name: "Cauldron Cakes",
        img: "https://thestarvingchefblog.com/wp-content/uploads/2022/05/cauldron-cake-recipe_200731_190950.jpg",
        timeToPrepare: "45 min",
        ingredients: ["butter", "flour", "cocoa powder", "bakinog powder", "allspice", "salt", "sugar", "vanilla", "buttermilk", "condensed milk", "food coloring", "sprinkles"],
        listOfSteps: ["Preheat oven to 180°C", "Combine flower, cocoa powder, baking powder, allspice & salt in a bowl", "In a separate bow, beat together he sugar and shortening and add egg and vanilla", "Slowly beat everything together", "Bake for about 20min", "For topping start combing water and cornstarch", "Beat together the remaining ingrediënts", "Carve a hole in the baked cakes", "Sppon the goo topping in the hole", "Accio cauldron cakes"],
        cuisine: "movie",
        favorite: false
    },
    {
        name: "Los Pollos Hermanos Chicken",
        img: "https://geekeat.files.wordpress.com/2015/02/los-pollos-hermanos-final-1-1500.jpg?w=660",
        timeToPrepare: "45 min",
        ingredients: ["lime juice", "orange juice", "sour cream", "garlic", "chili powder", "cumin", "cayenne pepper", "seasoning blend", "dried oregano", "chicken tenders", "large eggs", "hot sauce", "flour", "corn flour", "lard"],
        listOfSteps: ["Combine the lime juice with all the herbs and seasonings", "Add chicken tenders and let them marinate in fridge overnight", "Let it sit at roomteperature for 20min", "Add together some hot sauce and eggs and season the sauce", "Heat some frying oil to 190°C", "Dip the chicken in the egg mixture and coat it in flour", "Fry the chicken for about 8-10min", "Fry some fries while you let the chicken rest on paper"],
        cuisine: "movie",
        favorite: true
    },
    {
        name: "Chicken curry",
        img: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Chicken_curry_in_a_pot.jpg/220px-Chicken_curry_in_a_pot.jpg",
        timeToPrepare: "45 min",
        ingredients: ["chicken breasts", "onion", "ginger", "garlic", "curry powder", "turmeric", "tomatoes", "coconut milk", "vegetable oil", "salt", "pepper"],
        listOfSteps: ["Marinate chicken breasts with ginger, garlic, and curry powder for 30 minutes",
            "Saute onion in oil until softened, then add ginger, garlic, and curry powder",
            "Stir in tomatoes and coconut milk, and bring to a simmer",
            "Add chicken breasts and cook until tender, about 20-30 minutes",
            "Season with salt and pepper to taste"],
        cuisine: "Indian",
        favorite: true
    },
    {
        name: "Shakshuka",
        img: "https://www.simplyrecipes.com/wp-content/uploads/2019/01/shakshuka-1-3-720x405.jpg",
        timeToPrepare: "20 min",
        ingredients: ["4 tablespoons olive oil", "1 medium onion, finely chopped", "2 cloves garlic, minced", "1 tablespoon ground cumin", "1 teaspoon paprika", "1/2 teaspoon turmeric", "1/4 teaspoon cayenne pepper (optional)", "1/4 teaspoon salt", "1/4 teaspoon black pepper", "4 large eggs", "1 (14.5-ounce) can diced tomatoes, undrained", "1/4 cup chopped fresh parsley"],
        listOfSteps: ["Heat the olive oil in a large skillet over medium heat. Add the onion and cook until softened, about 5 minutes. Add the garlic, cumin, paprika, turmeric, cayenne pepper (if using), salt, and pepper and cook for 1 minute more, stirring constantly.",
            "Pour in the diced tomatoes and bring to a simmer. Reduce heat to low and simmer for 10 minutes, stirring occasionally.",
            "Make 4 wells in the sauce with the back of a spoon. Crack an egg into each well.",
            "Cover the skillet and cook for 10-12 minutes, or until the whites are set and the yolks are cooked to your liking.",
            "Sprinkle with parsley and serve immediately with warm pita bread"],
        cuisine: "Middle Eastern",
        favorite: true
    },
    {
        name: "Pilau Rice",
        img: "https://www.allrecipes.com/recipe/227446/fried-chicken-and-pilaf-rice/",
        timeToPrepare: "45 min",
        ingredients: ["2 cups basmati rice", "2 tablespoons vegetable oil", "1 large onion, chopped", "2 cloves garlic, minced", "1 tablespoon grated ginger", "1 teaspoon turmeric", "1 teaspoon ground cumin", "1/2 teaspoon salt", "1/4 teaspoon black pepper", "1 (14.5-ounce) can diced tomatoes, undrained", "1 cup chopped fresh parsley", "1/2 cup chopped fresh cilantro"],
        listOfSteps: ["Rinse the rice under cold running water until the water runs clear.",
            "In a large pot, heat the oil over medium heat. Add the onion and cook until softened, about 5 minutes. Add the garlic, ginger, turmeric, cumin, salt, and pepper and cook for 1 minute more, stirring constantly.",
            "Add the rice and stir to coat with the spices. Pour in the diced tomatoes and bring to a boil.",
            "Reduce heat to low, cover, and simmer for 20 minutes, or until the rice is cooked through.",
            "Fluff the rice with a fork and stir in the parsley and cilantro.",
            "Heat 2 tablespoons of oil in a large skillet over medium heat. Add the rice and cook until golden brown on all sides, about 5 minutes.",
            "Serve hot with chapati"],
        cuisine: "Indian",
        favorite: true
    },
    {
        name: "Chapati",
        img: "https://www.bbcgoodfood.com/recipes/naan-and-chapatis",
        timeToPrepare: "20 min",
        ingredients: ["2 cups all-purpose flour", "1 teaspoon salt", "1/4 cup vegetable oil", "1/2 cup warm water", "vegetable oil", "flour"],
        listOfSteps: ["In a large bowl, whisk together the flour and salt.",
            "Drizzle in the oil and mix until the dough comes together.",
            "Add the warm water a little at a time, stirring until a soft dough forms.",
            "Knead the dough for 5-10 minutes, or until smooth and elastic.",
            "Cover the dough with plastic wrap and let it rest for 30 minutes.",
            "Divide the dough into 12 equal pieces.",
            "On a lightly floured surface, roll out each piece of dough into a thin circle, about 12 inches in diameter.",
            "Heat a large skillet over medium heat.",
            "Place the rolled-out chapati in the skillet and cook for about 1 minute per side, or until golden brown.",
            "Drizzle with oil and cook for another minute per side, or until puffed up.",
            "Serve hot with fried pilau rice"],
        cuisine: "Indian",
        favorite: true
    },
    {
        name: "Muamba de Galinha",
        img: "https://www.cozinharsemstress.pt/cozinhar/wp-content/uploads/2019/02/A-001-3741.jpg",
        timeToPrepare: "2 hours",
        ingredients: [
            "1 whole chicken, cut into pieces",
            "2 tablespoons red palm oil",
            "1 large onion, finely chopped",
            "3 cloves of garlic, minced",
            "2 ripe tomatoes, diced",
            "1 red bell pepper, chopped",
            "1 green bell pepper, chopped",
            "1 cup okra, sliced (optional)",
            "2 tablespoons tomato paste",
            "1-2 teaspoons peri-peri sauce or hot sauce (adjust to taste)",
            "1 teaspoon ground ginger",
            "1 teaspoon ground cumin",
            "1 teaspoon ground coriander",
            "1 teaspoon smoked paprika",
            "Salt and pepper to taste",
            "2 bay leaves",
            "2 cups chicken broth",
            "Fresh cilantro or parsley for garnish",
        ],
        listOfSteps: [
            "Marinate the Chicken:",
            "1. In a large bowl, season the chicken pieces with salt, pepper, ground ginger, ground cumin, ground coriander, and smoked paprika. Let it marinate for at least 30 minutes.",
            "Prepare the Vegetables:",
            "2. In a large pot, heat the red palm oil over medium heat. Add the chopped onions and sauté until they are soft and golden.",
            "Add Aromatics:",
            "3. Add the minced garlic and sauté for an additional minute until fragrant.",
            "Cook the Chicken:",
            "4. Add the marinated chicken pieces to the pot and brown them on all sides.",
            "Add Vegetables:",
            "5. Stir in the diced tomatoes, chopped red and green bell peppers, and sliced okra (if using). Cook for a few minutes until the vegetables are slightly softened.",
            "Spice it Up:",
            "6. Add the tomato paste, peri-peri sauce or hot sauce, and bay leaves. Mix well to coat the chicken and vegetables with the spices.",
            "Pour in Chicken Broth:",
            "7. Pour in the chicken broth, bring the mixture to a boil, then reduce the heat to low. Cover the pot and let it simmer for about 30-40 minutes, or until the chicken is cooked through and tender.",
            "Adjust Seasoning:",
            "8. Taste and adjust the seasoning with salt, pepper, and additional spices if needed.",
            "Serve:",
            "9. Remove the bay leaves. Serve the Muamba de Galinha hot over rice or with a side of funge (a traditional Angolan staple made from cassava).",
            "Garnish:",
            "10. Garnish with fresh cilantro or parsley before serving.",
            "Enjoy your delicious Angolan Muamba de Galinha!",
        ],
        cuisine: "Angolan",
        favorite: true,
    },
    {
        name: "Pasteis de Nata",
        img: "https://cdn.heelhollandbakt.nl/2023/03/Pastel-de-nata-950x550.jpg",
        timeToPrepare: "1.5 hours",
        ingredients: [
            "2 sheets of puff pastry (store-bought or homemade)",
            "Flour (for dusting)",
            "2 cups whole milk",
            "1 cinnamon stick",
            "1 lemon peel (wide strips)",
            "1 cup granulated sugar",
            "4 tablespoons all-purpose flour",
            "4 tablespoons cornstarch",
            "6 large egg yolks",
            "1 teaspoon vanilla extract",
            "Powdered sugar (for dusting)",
            "Ground cinnamon (for dusting)",
        ],
        listOfSteps: [
            "Prepare the Pastry:",
            "1. If using store-bought puff pastry, roll it out on a floured surface to about 1/8 inch thickness.",
            "2. Cut the pastry into squares that will fit into the cups of a muffin tin.",
            "3. Line each cup of the muffin tin with the pastry, pressing it into the bottom and up the sides. Ensure there is some overhang.",
            "Prepare the Custard Filling:",
            "4. In a saucepan, heat the milk, cinnamon stick, and lemon peel over medium heat until it begins to simmer. Remove from heat and let it cool slightly.",
            "5. In a separate bowl, whisk together sugar, flour, and cornstarch.",
            "6. Gradually whisk the dry ingredients into the warm milk until well combined.",
            "7. Return the mixture to the heat and cook, stirring continuously until it thickens.",
            "8. In a separate bowl, beat the egg yolks. Gradually add a small amount of the hot milk mixture to the eggs, stirring constantly to temper the eggs.",
            "9. Pour the egg mixture back into the saucepan with the milk, whisking continuously.",
            "10. Continue cooking and stirring until the custard is thick and smooth. Remove from heat and stir in the vanilla extract.",
            "Assemble and Bake:",
            "11. Preheat your oven to 475°F (245°C).",
            "12. Fill each pastry-lined cup with the custard mixture, leaving a small space at the top.",
            "13. Bake in the preheated oven for about 12-15 minutes or until the pastry is golden and the custard is lightly browned on top.",
            "14. Remove from the oven and let the custard tarts cool in the tin for a few minutes.",
            "Serve:",
            "15. Carefully remove the custard tarts from the muffin tin and place them on a wire rack to cool completely.",
            "16. Dust with powdered sugar and ground cinnamon before serving.",
            "17. Enjoy your delicious Pasteis de Nata!",
        ],
        cuisine: "Portuguese",
        favorite: true,
    },
    {
        name: "Msemen",
        img: "https://ohmyfoodness.nl/wp-content/uploads/2020/07/msemmen-2.jpg",
        timeToPrepare: "2 hours",
        ingredients: [
            "4 cups all-purpose flour",
            "1 cup fine semolina",
            "1 teaspoon salt",
            "1 tablespoon sugar",
            "1 tablespoon active dry yeast",
            "1 1/2 to 2 cups warm water",
            "1/4 cup vegetable oil",
            "Butter or vegetable oil (for brushing)",
        ],
        listOfSteps: [
            "In a large bowl, mix the flour, semolina, salt, sugar, and yeast.",
            "Gradually add warm water and knead until you get a soft and elastic dough. You may need more or less water, so add gradually.",
            "Once the dough is well-kneaded, cover it and let it rest for about 10-15 minutes.",
            "Divide the dough into small balls (about the size of a golf ball).",
            "Take each ball, dip it in vegetable oil, and flatten it into a thin rectangle on an oiled surface.",
            "Fold the sides of the rectangle towards the center to create a square shape. Brush with more oil if needed.",
            "Repeat the process with the remaining balls, and let the msemen rest for about 30 minutes, covered.",
            "Heat a griddle or non-stick pan over medium heat. Cook each msemen square on both sides until golden brown and cooked through.",
            "Brush each cooked msemen with butter or oil for added flavor.",
            "Serve warm and enjoy your delicious Msemen!",
        ],
        cuisine: "Moroccan",
        favorite: true,
    },
    {
        name: "Meatball Burrito",
        img: "https://farmrich.com/wp-content/uploads/2017/03/FR-000019-Recipe-MB-Burrito_v1.jpg",
        timeToPrepare: "30 minutes",
        ingredients: [
            "1 pound ground beef",
            "1/2 cup breadcrumbs",
            "1/4 cup grated Parmesan cheese",
            "1 egg, beaten",
            "1 teaspoon garlic powder",
            "1 teaspoon onion powder",
            "Salt and pepper to taste",
            "1 cup cooked rice",
            "1 cup black beans, drained and rinsed",
            "1 cup shredded cheese (cheddar or Mexican blend)",
            "Flour tortillas",
            "Salsa, guacamole, sour cream (optional, for serving)",
        ],
        listOfSteps: [
            "Preheat your oven to 375°F (190°C).",
            "In a large bowl, combine ground beef, breadcrumbs, Parmesan cheese, beaten egg, garlic powder, onion powder, salt, and pepper. Mix until well combined.",
            "Shape the mixture into meatballs and place them on a baking sheet lined with parchment paper.",
            "Bake the meatballs in the preheated oven for about 20 minutes or until cooked through and browned on the outside.",
            "In a large skillet, heat cooked rice and black beans over medium heat until warmed through.",
            "Warm the flour tortillas in a dry skillet or microwave according to the package instructions.",
            "Assemble the burritos by placing a spoonful of rice and black beans on each tortilla. Add meatballs and sprinkle with shredded cheese.",
            "Fold the sides of the tortilla over the filling and roll it into a burrito.",
            "Optional: Serve with salsa, guacamole, and sour cream on the side.",
            "Enjoy your delicious Meatball Burrito!",
        ],
        cuisine: "Mexican",
        favorite: true,
    },
    {
        name: "Arkhan the Cruel's Flame-Roasted Halfling Chili (vegetarian version)",
        img: "https://i.redd.it/szpu4cpcepz51.jpg",
        timeToPrepare: "60 mins",
        ingredients: [
            "1 ½ tbsp unsweetened cocoa powder",
            "1 ½ tbsp chili powder",
            "1 ¼ tsp ground cinnamon",
            " 1 ½ tsp oregano",
            " ¾ tsp cumin",
            "½ tsp allspice",
            "¼ tsp cloves",
            "¼ tsp cayenne",
            "salt & freshly ground black pepper",
            "5 garlic cloves",
            "2 15oz cans red kidney beans",
            "2 cups vegetable broth",
            "1 large yellow onion, chopped",
            "1 15oz cans tomato puree",
            "2 tsp brown sugar",
            "1 lbs of vegetarian minced meat",
            "1 tsp of apple cider vinegar"
        ],
        listOfSteps: [
            "Mix all the spices.",
            "Open and wash one can of kidney beans. In a blender, puree the beans with 3/4 cup of the vegetable broth. Open and wash the other can as well.",
            "Over medium heat, melt butter and/or vegetable oil. Fry the chopped onions until soft.",
            "Add the spice mixture, stir for about a minute.",
            "Add the remaining 1 ¼ cup of vegetable broth and stir it up, scraping the bottom of the pot to loosen any browned bits.",
            "As soon as the broth is bubbling, add the tomato puree, the bean-broth mixture, and the brown sugar. Slowly stir until blended.",
            "Add the remaining can of kidney beans and the minced meat - stir to incorporate.",
            "Turn up the heat to medium-high. Once bubbling, turn back down to medium-low and let simmer for about 30 minutes.",
            "As a finishing touch, add a splash of apple cider vinegar and stir to incorporate.",
            "Serve with spring onions, shredded cheddar, avocado, sour cream, crackers, or other complementary sides of your liking."
        ],
        cuisine: "British",
        favorite: true
    },
    {
        name: "Feijoada",
        img:"https://www.foodandwine.com/thmb/be5HJEGNvEWllb-iYsML_DghtJ8=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Feijoada-FT-RECIPE0323-2ed2fbae5e0c4110b5bb522c6d7e0eac.jpg",
        timeToPrepare: "3 hrs",
        ingredients: [
            "500g dry black beans (soaked overnight)",
            "1 tablespoon olive oil",
            "150g slab bacon, diced",
            "500g pork ribs, cut into individual ribs",
            "2 Mexican chorizo sausages, sliced",
            "1 smoked sausage, sliced",
            "1 large onion, chopped",
            "4 cloves garlic, minced",
            "3 tomatoes, diced",
            "Salt and pepper",
            "3 bay leaves",
            "white rice (for serving)",
            "farofa (for serving)",
        ],
        listOfSteps: [
            "In a large bowl with water, soak beans overnight.",
            "When you are ready to make your stew, in a large heavy-bottom soup pot, over medium heat, add the oil and bacon. Cook until crisp and transfer to a plate.",
            "Use the same saucepan to brown ribs and sausages in batches. (You will want to be sure to cook the sliced Mexican chorizo on its own, as it can be very greasy. Drain the grease before continuing.) Set each aside as cooked.",
            "If needed, add more oil to the pan. On medium-high, sauté onion, and garlic until soft and translucent, about 5 minutes. Add tomatoes and cook for another 3 minutes.",
            "Drain and rinse the soaked beans. Add them to the pot along with the ribs, bacon, sausages, salt, pepper, and bay leaf. Cover with water (about 8 cups).",
            "Bring the mixture to a boil and reduce the heat to low. Cover and let it cook for 2 to 2 and a half hours, or until the beans are soft.",
            "If the stew is too liquidy, uncover the saucepan and continue to cook for another 20 minutes to allow some of the liquid to evaporate.",
            "Serve with white rice and sprinkle some farofa on top.",
        ],
        cuisine: "brazilian",
        favorite: false,
    },
    {
        name: "Brigadeiro",
        img:"https://upload.wikimedia.org/wikipedia/commons/a/a4/Brigadeiro.jpg",
        timeToPrepare: "15 min",
        ingredients: [
            "1 can (397 grams) sweetened condensed milk",
            "4 tablespoons unsweetened cocoa powder",
            "2 tablespoon butter",
            "Chocolate sprinkles or any other you prefer",
        ],
        listOfSteps: [
            "Grease a plate with butter and set aside.",
            "In a medium non-stick pan, combine the condensed milk, butter, and cocoa powder in medium heat and mix it well.",
            "The mixture thickens after about 10-12 minutes, and once you can run your silicone spatula through the middle of it without it running back together for 2-3 seconds, it is done.",
            "Pour the mixture onto the lightly greased plate and let it chill in the fridge for an hour.",
            "In the meantime, prepare the candy cups and place the sprinkles in a bowl.",
            "Once chilled, you are ready to roll the little balls. Lightly wet your hands, put a tablespoon of the chewy mixture on your hands, and roll into a small ball.",
            "Roll it over the sprinkles.",
            "Place the balls in the candy cups, and voila! Enjoy it!",
        ],
        cuisine: "brazilian",
        favorite: true,
    },
    {
        name: "Spaghetti Bolognese",
        img: "https://www.recipetineats.com/wp-content/uploads/2018/07/Spaghetti-Bolognese_5.jpg",
        timeToPrepare: "40 min",
        ingredients: [
            "Pasta",
            "Tomato Sauce",
            "Beef",
            "Bay Leaves",
            "Thyme",
            "Beef Cube",
            "Onion & Garlic",
            "Red Wine (optional)"
        ],
        listOfSteps: [
            "Saute garlic and onion - about 3 minutes",
            "Brown the beef - about 2 minutes",
            "Add everything else, give it a good stir then simmer for 20 minutes minimum (midweek), up to 3 hours (weekend indulgence!). Slow cooking makes the beef incredibly tender and the sauce develops extra flavour."
        ],
        cuisine: "Italian",
        favorite: true
    },
    {
        name: "Lunchbox Pizza Bread",
        img: "https://www.recipetineats.com/wp-content/uploads/2023/02/Lunchbox-pizza-bread_8-1.jpg",
        timeToPrepare: "1 hour 15 min",
        ingredients: [
            "300 g plain flour",
            "1 1/2 tsp baking powder",
            "1/2 tsp baking soda / bi-carb soda",
            "1/2 tsp cooking/kosher salt",
            "1 large egg", "250 ml milk",
            "50 g sour cream",
            "45 ml olive oil",
            "100 g shredded cheese",
            "150 g shredded cheese",
            "125 g pizza sauce",
            "1/4 red onion",
            "1/2 green capsicum / bell pepper",
            "40 g sliced kalamata olives",
            "50g/ 2 oz pepperoni slices"
        ],
        listOfSteps: [
            "Preheat oven to 180°C/350°F (160°C fan). Oil spray a 23 x 33 cm metal pan then line with baking / parchment paper.",
            "Whisk Dry ingredients in a large bowl.",
            "Whisk Wet ingredients in a separate bowl until combined.",
            "Combine Wet & Dry - Pour Wet into the Dry ingredients. Mix with a rubber spatula until the flour is mostly mixed in but you can still see a bit of flour. Add cheese then stir until you can no longer see flour. Some small lumps is fine, they will bake out.",
            "Assemble - Scrape into the baking pan and evenly spread - it's not that thick, remember it rises! Spread the surface with pizza sauce. Sprinkle with cheese, then (in this order) onion, capsicum, olives then pepperoni",
            "Bake 40 min - Bake 25 minutes uncovered. Cover with a baking tray (or foil) then bake for a further 15 minutes.",
            "Cool 10 minutes in the pan then use the paper overhang to lift or slide out onto a cooling rack. Cool for a further 10 minutes before slicing to serve.",
            "Serving - Great at room temp though for VIP's, sometimes I warm it in the oven, drizzle with a swish of olive oil and sprinkle with a pinch of oregano."
        ],
        cuisine: "Western",
        favorite: false
    },
    {
        name: "Vietnamese Caramel Ginger Chicken",
        img: "https://www.recipetineats.com/wp-content/uploads/2023/08/Vietnamese-Ginger-Caramel-Chicken_8.jpg",
        timeToPrepare: "15 min",
        ingredients: [
            "1 kg / 2 lb skinless chicken thigh fillets",
            "45 ml fish sauce", "1 birds eye chilli or Thai chilli",
            "45 ml vegetable oil",
            "50 g brown sugar",
            "1/3 cup ginger",
            "2 eschallots",
            "125 ml boiling water",
            "Fresh coriander/cilantro or green onion slices",
            "Red chilli",
            "Jasmine rice, white rice or plain rice"
        ],
        listOfSteps: [
            "Toss chicken with fish sauce and chilli, then set aside while you prepare the other ingredients. You could marinate even overnight but it's not necessary.",
            "Pan size - Use a large non-stick pan. Else, be prepared to remove chicken at end to speed up sauce reduction.",
            "Caramel - Mix oil and sugar in the cold pan, then turn onto medium high heat. As soon as the sugar is melted, remove the pan from the stove then carefully add the chicken. Add ginger and shallots, toss briefly. The caramel may harden, that's ok, it will re-melt.",
            "Cook outside of chicken - Then put the pan back on the stove and stir just until the chicken changes from pink to white all over, but not browned, and definitely not cooked through.",
            "Simmer 10 min - Add water, stir, bring to a simmer. Simmer very rapidly, still on medium high (or even high!), for 10 to 12 minutes, until the liquid reduces right down to a glaze. It might take longer if your pan is smaller or your stove is weaker, that's ok. Stir every now and then while watery, then once it's reduced down to a glaze, toss regularly to get nice colour on the chicken. The further you take it, the better the colour!",
            "Serve with jasmine rice or other plain rice garnished with extra slices of chilli and fresh coriander if desired. Smashed cucumbers or Asian Slaw would be a terrific side!"
        ],
        cuisine: "Vietnamese",
        favorite: false
    },
    {
        name: "Tequila Sunrise",
        img: "https://www.recipetineats.com/wp-content/uploads/2019/09/Tequila-Sunrise.jpg",
        timeToPrepare: "5 min",
        ingredients: [
            "45 ml / 1.5oz tequila",
            "90ml / 3 oz orange juice",
            "15 ml / 0.5 oz grenadine syrup",
            "Orange slices",
            "Maraschino cherry"
        ],
        listOfSteps: [
            "Pour tequila and orange juice in a tall glass. Scale up recipe as required for your glass side (1 part tequila to 3 parts OJ)!",
            "Mix, then fill with ice.",
            "Drizzle grenadine down the side of the glass over the back of a teaspoon. Do not mix!",
            "Garnish with orange slice and Maraschino cherry. Serve immediately!"
        ],
        cuisine: "Tropical",
        favorite: true
    },
]

let visitations = []

food.forEach(fooditem => {
    const visitationItem = {
        name: fooditem.name,
        count: 0
    }

    visitations.push(visitationItem)
});

export {food, visitations}

export default food
